### ISSUE TITLE
Ability to use hardware buttons on the printer to send a scan to linux

### ISSUE THREAD

**Issue by aravind3626** [ThierryHFR/scangearmp2#64]
Windows has this Canon IJ Network Selector Tool which gets installed along with the Canon IJ Scan utility in Widnows sends some kind of packet sequence to Canon printers so that computer is visible to the printer and can be selected to send a scan directly to it.

Is is possible for you to integrate such a script for linux to achieve the same?

Brother printers have such a script called brscan to achieve the same.

Note: I have tried scanbd and similiar utilites which uses usb to scan for the button events but I am looking for network implementation for the same.

**Comment by ThierryHFR** [comment]
@aravind3626 ,
The driver does not provide this option. You need a tool that detects the button action.
Can you provide me with this trace, and I'll get back to you. 
```
tcpdump ip host ip-your-device -w your-device.pcap
```

**Comment by ThierryHFR** [comment]
no feedback
